# Set path to your private settings directory
private_settings_dir: ~/private_settings/ssh/templates/

# Set your git email and name
git_email: "mymail@mail.com"
git_name: "My Name"

additional_homebrew_cask_packages:
  - fastlane
  - mysqlworkbench
