homebrew_cask_packages:
  - android-studio
  - appcleaner
  - atom
  - clipy
  - docker
  - google-chrome
  - google-japanese-ime
  - iterm2
  - jetbrains-toolbox
  - magican
  - sequel-pro
  - skitch
  - slack
  - sourcetree
  - vagrant
  - virtualbox
