homebrew_cask_packages:
  - android-studio-canary
  - appcleaner
  - atom
  - clipy
  - google-chrome
  - google-japanese-ime
  - iterm2
  - java
  - jetbrains-toolbox
  - magican
  - sequel-pro
  - skitch
  - slack
  - sourcetree
  - vagrant
