- name: Setup private PC environment
  hosts: private
  connection: local
  gather_facts: no
  roles:
    # Application install
    - brew
    - brew-cask
    # settings
    - ssh
    - zsh
    - git
    - vim
    - atom
- name: Setup company PC environment
  hosts: biz
  connection: local
  gather_facts: no
  roles:
    # Application install
    - brew
    - brew-cask
    # settings
    - ssh
    - zsh
    - git
    - vim
    - atom
- name: Setup company linux server environment
  hosts: biz-linux
  connection: local
  gather_facts: no
  roles:
    # settings
    - ssh
    - zsh
    - git
    - vim
