- name: upgrade pip
  pip:
    name: pip
    executable: pip3
    state: latest
  tags:
    - pip

- name: Install python packages globally
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pip_packages }}"
  when:
    - pip_packages is defined
  tags:
    - pip
