atom_packages:
  - atom-typescript
  - autocomplete-python
  - editorconfig
  - file-icons
  - linter
  - linter-tslint
  - python-tools
  - regex-railroad-diagram
  - script
  - terminal-plus
  - vim-mode-plus
