atom_packages:
  - atom-ternjs
  - atom-typescript
  - autocomplete-modules
  - autocomplete-python
  - busy-signal
  - editorconfig
  - file-icons
  - intentions
  - linter
  - linter-eslint
  - linter-tslint
  - linter-ui-default
  - python-tools
  - regex-railroad-diagram
  - script
  - terminal-plus
  - vim-mode-plus
  - markdown-pdf
