- name: Install homebrew
  shell: |
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  tags:
    - brew

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"
  when:
    - homebrew_taps is defined
  tags:
    - brew

- name: Add additional homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - "{{ additional_homebrew_taps }}"
  when:
    - additional_homebrew_taps is defined
  tags:
    - brew

- name: Update homebrew & upgrade all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - brew

- name: Install homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: latest
    upgrade_all: yes
  when:
    - homebrew_packages is defined
  tags:
    - brew

- name: Install additional homebrew packages
  homebrew:
    name: "{{ additional_homebrew_packages }}"
    state: latest
    upgrade_all: yes
  when:
    - additional_homebrew_packages is defined
  tags:
    - brew
