- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
    greedy: yes
  tags:
    - brew-cask

- name: Add additional homebrew cask packages
  homebrew_cask:
    name: "{{ additional_homebrew_cask_packages }}"
    state: present
    greedy: yes
  when:
    - additional_homebrew_cask_packages is defined
  tags:
    - brew-cask

- name: Install iTerm2 Shell Integration
  shell: curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
  tags:
    - brew-cask
